apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: 
  POSTGRES_USER: 
  POSTGRES_PASSWORD:
 
---

apiVersion: v1
kind: Secret
metadata:
  name: poi-aws-secret
  labels:
    app: poi
data:
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
 